spring:
  application:
    name: Ms-07Controlpostadopcion

  datasource:
    url: jdbc:mysql://localhost:3306/visitas_db
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8087

springdoc:
  api-docs:
    enabled: true
    version: openapi_3_0
  swagger-ui:
    enabled: true

 eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/